from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('', views.entry_list, name='toph_lawfirm_entry_list'),
    path('entry/edit/<int:pk>/', views.edit_entry, name='edit_entry'),
    path('lodge/edit/<int:pk>/', views.edit_lodge, name='edit_lodge'),
    path('review/edit/<int:pk>/', views.edit_review, name='edit_review'),
    path('entry/<int:pk>/', views.entry_detail, name='entry_detail'),
    path('delete-entry/<int:pk>/', views.delete_entry, name='delete_entry'),
    path('delete-approval/<int:pk>/', views.delete_approval, name='delete_approval'),
    path('delete-document/<int:pk>/', views.delete_document, name='delete_document'),
    path('delete-party/<int:pk>/', views.delete_party, name='delete_party'),
    path('entry-details/<int:pk>/', views.entry_details, name='entry_details'),
    path('login/', views.custom_login, name='toph_lawfirm_login'),
    path('select-council/', views.select_council, name='toph_lawfirm_select_council'),
    path('logout/', views.custom_logout.as_view(), name='toph_lawfirm_logout'),
    path('draft173/', views.handle_draft_form, name='toph_lawfirm_draft173'),
    path('docusign/', views.send_document_for_signing, name='toph_lawfirm_docusign'),
    path('lodge/', views.send_lodge_email, name='toph_lawfirm_lodge'),
    path('entry/<int:pk>/update_dealing_number/', views.update_dealing_number, name='update_dealing_number'),
    path('thank-you/', views.ThankYouPageView.as_view(), name='thank_you'),
    path('upload-document/<int:pk>/', views.upload_document, name='upload_document'),
    path('get-document/<int:pk>/', views.get_documents_for_entry, name='get_documents_for_entry'),
    path('upload-party/<int:pk>/', views.upload_party, name='upload_party'),
    path('get-party/<int:pk>/', views.get_parties_for_entry, name='get_parties_for_entry'),
    path('add-entry/', views.add_entry, name='add_entry'),
    path('get-entry/', views.get_entries, name='get_entries'),
    path('get-review/<int:pk>/', views.get_reviews_for_approval, name='get_reviews_for_approval'),
    path('upload-review/', views.upload_review, name='upload_review'),
    path('send-reminder-emails/', views.send_reminder_emails, name='send_reminder_emails'),
    path('edit-council-info/', views.edit_council_info, name='edit_council_info'),
    path('set-approval-outcome/', views.set_approval_outcome, name='set_approval_outcome'),
    path('share-tracking/', views.share_tracking, name='share_tracking'),
    path('get-documents-lodged/<int:pk>/', views.get_documents_lodged, name='get_documents_lodged'),
]